### PR TITLE
add GitHub Actions workflow CI

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by JFCote** [comment]
Hi @sullis 
Can you please add a bit of background about what exactly this is about?
We currently test our build using Travis CI so I'm not sure why we would like to do something with Github Actions. But maybe I just don't understand the PR.

Please add more information and I will review it!
Thanks

**Comment by cbornet** [comment]
The workers on GitHub CI are much more powerful than Travis.

**Comment by JFCote** [comment]
@cbornet I believe you. But I would like to know more about why @sullis is proposing this PR. I'm not sure I want to move to Github action at the moment. :)

**Comment by sullis** [comment]
in my limited experience, building code on GitHub Actions is faster than building code on TravisCI.   

After merging this PR, you can compare the build speed for this project.

**Comment by JFCote** [comment]
@sullis Thanks for the explanation. We don't only build in Travis, we do our unit testing and our test coverage validation. Is it supported in Github Action?

Anyway, I will take the holiday break to read more on this and will merge in the upcoming weeks when I will understand better the implication. 

Thanks for your PR and it should be merged when I'll come back in January.
Happy holidays!

**Comment by sullis** [comment]
fyi: the Micronaut project switched from TravisCI to GitHub Actions

micronaut-github-actions

**Comment by JFCote** [comment]
Let's try this and if it work well, we'll convert everything to Github actions. Thanks @sullis

**Pull request merged**
