### PR TITLE
Resolve #606: add schema naming convention validation

### LINKED ISSUE #606: Schema name validation feature
**Is your feature request related to a problem? Please describe.**
I would like to use the validator to validate schema names with naming conventions also, like property, path, query, etc.

**Describe the solution you'd like**
Configuring the naming convention in the options.json, and the validator checks the schema names.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by tothgergely92**

### CODE REVIEW

**Comment by JFCote** [comment]
@tothgergely92 Thanks for the PR. I'll give it a closer look in the upcoming days!

**Comment by JFCote** [comment]
@tothgergely92 I'm sorry for the delay in the review, been very busy latety both at my job and in my personal life. Will definitely review this next week. Thanks for your understanding.

**Review by JFCote — APPROVED** [review]
LGTM! Thanks for your contribution!!

**Comment by JFCote** [comment]
@tothgergely92 I don't know, we have done not so long ago. Do you need this very soon or are you able to use the compiled version in your workflow?

**Comment by tothgergely92** [comment]
I am able to use the locally built jar, so it is a nice to have, to use the officially published package from a public repo.

**Pull request merged**
