### PR TITLE
[#520] PascalCase Support

### PR DESCRIPTION
**Pull request by dchauhan-twilio**
* Adds support for validating based on PascalCase.

Related to discussion [Pascal Case Support](#520) feature request.

### CODE REVIEW

**Comment by dchauhan-twilio** [comment]
@JFCote this is my first pass at this change. When you get a chance, please review.

**Review by JFCote — APPROVED** [review]
LGTM! Thanks for your contribution!

**Comment by JFCote** [comment]
@dchauhan-twilio I will need to check with another maintainer how and when we can do a new release. Unfortunately, the process of making a release with this project is not fully automated and requires some manual work. I'm planning on maybe use Github Maven but didn't had the time yes.
@jmini Could you do a new release of the project? Thanks and let me know if I can help.

**Comment by dchauhan-twilio** [comment]
Understood. Thanks for your help. I will keep an eye out for the next release as we would only be able to consume this via maven.

**Comment by dchauhan-twilio** [comment]
@JFCote I will do some more testing tomorrow. Ideally we would like this asap so we can start using today.

**Comment by JFCote** [comment]
@dchauhan-twilio I will not be able to provide you with a valid maven version today as this is a side project and I have a fulltime job and a family and limited time in a day. In normal time, @jmini takes care of the releases but I can't reach him, he might be on vacation or something. That being said, if you want to check if it works, you can simply build the project and get the jar file for the CLI. Then, follow the instruction here:  https://github.com/OpenAPITools/openapi-style-validator#to-launch

You should be able to see if it works and validate your file. I understand that you would love to have this in your build using Maven/Gradle but maybe this will do the trick while I figure out a way to release this project.

**Comment by JFCote** [comment]
@dchauhan-twilio we released version 1.9 yesterday! Enjoy!

**Comment by dchauhan-twilio** [comment]
@JFCote thank you so much. Understand you are busy so appreciate the quick turn around. Was actually going to offer helping with the deploy pipeline but you beat me to releasing it.

**Comment by JFCote** [comment]
@dchauhan-twilio In fact, I didn't add anything, but I asked @wing328 who is the admin of the complete OpenAPITools organization. He took care of the release the old fashion way :)

**Pull request merged**
