### PR TITLE
Add signing task

### PR DESCRIPTION
**Pull request by jmini**
Add signing as additional step: signing

This is required to publish to maven central.

Related issue #10

### CODE REVIEW

**Comment by jmini** [comment]
I have run:
`./gradlew publishToSonatype`

```
* What went wrong:
Execution failed for task ':cli:publishMavenJavaPublicationToSonatypeRepository'.
> Failed to publish publication 'mavenJava' to repository 'sonatype'
   > Could not write to resource 'https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapistylevalidator/openapi-style-validator-cli/1.1-SNAPSHOT/openapi-style-validator-cli-1.1-20190822.155614-2-all.jar'.
      > Read timed out
```

Partial result can be seen on the distant repo:
https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapistylevalidator/

**Comment by JFCote** [comment]
Ok well good try. I'm sure we're very close. I'll take a look next week :)

**Comment by jmini** [comment]
This morning it was OK:

```
$ gw publishToSonatype

BUILD SUCCESSFUL in 21s
23 actionable tasks: 4 executed, 19 up-to-date
```

The results looks also good:
https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapistylevalidator/

* The `-SNAPSHOT` suffix is replaced with `-20190823.034828-2`.
* For each artifact we see the expected files:
  * `<artifactId>-<version>(-<qualifier>).jar` (publised by gradle)
     * `<artifactId>-<version>(-<qualifier>).jar.md5` (added by nexus)
     * `<artifactId>-<version>(-<qualifier>).jar.sha1` (added by nexus)
  * `<artifactId>-<version>(-<qualifier>).jar.asc` (publised by gradle)
     * `<artifactId>-<version>(-<qualifier>).jar.asc.md5` (added by nexus)
     * `<artifactId>-<version>(-<qualifier>).jar.asc.sha1` (added by nexus)

And the same for the pom (`pom` instead of `jar` without qualifier).

---

I think that we can try performing a `1.1` release and publish it to maven central.

**Comment by JFCote** [comment]
@jmini That looks good. Please go ahead (or let me know in Slack how I can perform it myself). Thanks!

**Pull request merged**
