### PR TITLE
ci: enable Java 14

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by JFCote** [comment]
@sullis please fix the problem with the compilation and I will merge it. 😀

**Comment by sullis** [comment]
We cannot merge this PR until we upgrade to Gradle 6.5.1
https://github.com/OpenAPITools/openapi-style-validator/pull/111

**Comment by JFCote** [comment]
@sullis You can merge the master in your branch and it should work now (#111 has been merged in the master)

**Comment by jmini** [comment]
I have merged `master` into this branch.

**Comment by JFCote** [comment]
@sullis and @jmini  : Even with latest gradle (in the master), it doesn't seems to be able to build. Any idea?

**Comment by JFCote** [comment]
@jmini Seems to be related to the Maven plugin, any ideas? Maybe some of the library we use is not compatible with java 14...

```
FAILURE: Build failed with an exception.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

Use '--warning-mode all' to show the individual deprecation warnings.
* What went wrong:
See https://docs.gradle.org/6.5.1/userguide/command_line_interface.html#sec:command_line_warnings
Execution failed for task ':maven-plugin:generateMavenPluginDescriptor'.
36 actionable tasks: 32 executed, 4 up-to-date
> Unsupported class file major version 58
```

**Comment by jmini** [comment]
I guess we should set the source and target compatibility values to Java 8 (done with https://github.com/OpenAPITools/openapi-style-validator/pull/142/commits/b267ceef213e4273f09de232055dfe21c60a936e)

**Comment by JFCote** [comment]
@sullis Can you try to update your branch with the master. It will probably fix the issue with java14 and I will be able to merge your change. Thanks

**Comment by jmini** [comment]
I have merged `origin/master` into this branch. Let's see how the CI is doing…

**Review by JFCote — APPROVED** [review]

**Pull request merged**
